// <auto-generated />
using System;
using HospitalzinhoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalzinhoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014201301_CriandoBancoDeDados")]
    partial class CriandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteContato", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("TelefoneCelular")
                        .HasColumnType("text");

                    b.Property<string>("TelefoneResidencial")
                        .HasColumnType("text");

                    b.HasKey("PacienteId");

                    b.ToTable("PacientesContatos");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteConvenio", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroCarteirinha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PacienteId");

                    b.ToTable("PacientesConvenios");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteEndereco", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PacienteId");

                    b.ToTable("PacientesEnderecos");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CPFMae")
                        .HasColumnType("text");

                    b.Property<string>("CPFPai")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Escolaridade")
                        .HasColumnType("integer");

                    b.Property<int?>("Etinia")
                        .HasColumnType("integer");

                    b.Property<int?>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("text");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeMae")
                        .HasColumnType("text");

                    b.Property<string>("NomePai")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteContato", b =>
                {
                    b.HasOne("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteModel", "Paciente")
                        .WithOne("Contato")
                        .HasForeignKey("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteContato", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteConvenio", b =>
                {
                    b.HasOne("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteModel", "Paciente")
                        .WithOne("Convenio")
                        .HasForeignKey("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteConvenio", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteEndereco", b =>
                {
                    b.HasOne("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteModel", "Paciente")
                        .WithOne("Endereco")
                        .HasForeignKey("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteEndereco", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("HospitalzinhoAPI.Models.Hospital.Paciente.PacienteModel", b =>
                {
                    b.Navigation("Contato");

                    b.Navigation("Convenio");

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
